FROM ubuntu:16.04

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
	apt-get install -y python3 && \
	apt-get install -y python3-pip && \
	pip3 install --upgrade pip && \
	pip3 install osgeo && \
	pip3 install pandas && \
	pip3 install scipy && \
	pip3 install -U statsmodels && \
	pip3 install spectral && \
	mkdir ./Tmp && \
	touch ./Tmp/MSaviFeat && \
	chmod 777 ./Tmp/MSaviFeat && \
	apt-get install -y zip && \
	apt-get install -y unzip && \
	apt-get install -y wget
